class_name Enums

enum CommandType {
	MOVE,
	MOVING_TO_UNIT,
	FOLLOWING,
	COLLECTING_RESOURCES_SEQUENTIALLY,
	AUTO_ATTACKING,
	CONSTRUCTING,
	ENTITY_IS_QUEUED,
	STRUCTURE_PLACED,
	ENTITY_PRODUCTION_CANCELED,
}